[tool.black]
line-length = 100
target-version = ["py311"]
exclude = """
(
  /(\\.git|\\.venv|env|venv|\\.mypy_cache|\\.pytest_cache|build|dist)/
  | ^\\.chroma/
  | ^data/
)
"""

[tool.ruff]
line-length = 100
target-version = "py311"
src = ["app", "domain", "use_cases", "infrastructure", "interface_adapters", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I"]  # pycodestyle/pyflakes + isort
ignore = ["E203", "E501"] # compat Black e linha longa já cuidada pelo Black

[tool.ruff.lint.isort]
known-first-party = ["app", "domain", "use_cases", "infrastructure", "interface_adapters", "tests"]
combine-as-imports = true

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
no_implicit_optional = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
pretty = true
ignore_missing_imports = true  # 3rd parties sem stubs
show_error_codes = true
exclude = [
  "\\.venv",
  "^data/",
  "^\\.chroma/",
  "^build/",
  "^dist/",
]

[tool.pytest.ini_options]
addopts = "-q"
